services:
  mirchibada-ai:
    build: .
    container_name: mirchibada-ai
    ports:
      - "3000:8080"
    volumes:
      - mirchibada-data:/app/backend/data
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBUI_JWT_SECRET=${JWT_SECRET}
      - WEBUI_NAME=Mirchibada AI
      - WEBUI_AUTH=true
      - SCARF_NO_ANALYTICS=true
      - DO_NOT_TRACK=true
      - ANONYMIZED_TELEMETRY=false
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mirchibada-data:
    name: mirchibada-data